<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>

<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/modal.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/configuracion.css">
<script src='<?=$this->base_url ?>/assets/js/dateTable.js'></script>

<script src='<?=$this->base_url ?>/assets/js/popper_core@2.js'></script>
<script src='<?=$this->base_url ?>/assets/js/tippy@6.js'></script>
<script>
$(document).ready(function() {
  tippy('#toolBuscar', {
    content: 'Agregar nuevo ',
  });
});

$(document).ready(function() {
  tippy('#toolEditar', {
    content: 'Editar ',
  });
});
</script>

<h1 class="h1">Configuracion </h1>


<div class="card" style="border-bottom-color: white; margin-top:15px;">
  <div class="card-body">


    <div class="row start-xs">

      <!--Primera card Departamento-->
      <div class="col-xs-6" style="    margin-top: 15px;">
        <div class="box">
          <div class="card" style="box-shadow: 0px 0px 24px 1px #8888884f;border: none;">
            <div
              style="background-color: #0e36a47a;margin-left: 20px;margin-right: 20px;margin-top: -21px; position: relative;height: 53px;border-radius: 5px;z-index: 0; ">

              <h3 style="margin-left: 10px;margin-top: 16px; color: white;">Gestionar departamento


                <div id="toolBuscar" style="float: right;">
                  <a href="#miModal" style="padding-right: 22px;color: white;">
                    <i class="fas fa-plus-circle"></i></a>
                </div>

              </h3>

            </div>

            <div class="card-body">

              <ul>
                <?php foreach ($this->departamento as $value) { ?>
                <li> <?= $value["nombre"] ?>
                  <a type="button" id="toolEditar"
                    onclick="editardepartamento( '<?= $value["id"] ?>', '<?= $value["nombre"] ?>')"><i
                      class="fa fa-pencil-square-o fa-2x" aria-hidden="true" style="color: coral;"></i></a>
                </li>
                <?php } ?>
              </ul>

            </div>
          </div>
        </div>
      </div>

      <!--Fin Primera card Departamento-->

      <!--segunda card Cargo-->
      <div class="col-xs-6" style="    margin-top: 15px;">
        <div class="box">
          <div class="card" style="box-shadow: 0px 0px 24px 1px #8888884f;border: none;">
            <div
              style="background-color: #0e36a47a;margin-left: 20px;margin-right: 20px;margin-top: -21px; position: relative;height: 53px;border-radius: 5px;z-index: 10; ">
              <h3 style="margin-left: 10px;margin-top: 16px; color: white;">Gestionar cargo y sueldo

                <div id="toolBuscar" style="float: right;">
                  <a href="#miModal1" style="padding-right: 22px;color: white;">
                    <i class="fas fa-plus-circle"></i></a>
                </div>
              </h3>

            </div>
            <div class="card-body">


              <div id="wrapper">

                <h3 style="text-align: center;">Para poder Editar el cargo debes Seleccionarlo <i
                    class="fas fa-check-double" style="color: #1ee81e;"></i></h3>


                <ul>
                  <?php foreach ($this->cargo as $value) { ?>
                  <li> <?= "{$value["nombre"]} -  {$value["salario_base"]} Bs." ?> <a type="button" id="toolEditar"
                      href="#" onclick="editarCargo('<?= $value["id"] ?>', event)"><i
                        class="fa fa-pencil-square-o fa-2x" aria-hidden="true" style="color: coral;"></i></a>
                    </a>
                  </li>
                  <?php } ?>
                </ul>



              </div>


            </div>
          </div>
        </div>
      </div>
      <!--Fin segunda card Cargo-->

    </div>

  </div>
</div>



<!-- //Modal departamento-->

<div id="miModal" class="modal" style=" z-index: 100;">

  <div class="modal-contenido">

    <div class="row"
      style="background-color: #0c4dc1;width: 100%;margin-left: 0px !important;margin-right: 0px !important;height:70px">
      <div class="col-xs-6" style="color: white;">
        <h2>Gestion Departamento</h2>
      </div>

      <div class="col-xs-6" style="text-align: end;top: 10px;margin-top: 17px;padding-right: 29px;">
        <a href="#" style="text-decoration: none;color: white;">X</a>
      </div>
    </div>

    <div class="row start-xs" style="margin-top: 40px;padding-left: 95px;padding-right: 95px;">

      <input type="hidden" id="input-departamento-id" />

      <div class="col-xs-12" style="margin-top: 25px;">
        <div class="omrs-input-group">
          <label class="omrs-input-filled">
            <input type="text" onkeypress="return soloLetras(event)" id="input-departamento-nombre" required
              style="background-color: white;   height: 50px;margin-top: -8px;">
            <span class="omrs-input-label">Departamento</span>
          </label>
        </div>
      </div>



      <div class="col-xs-12">
        <div style=" margin-top: 25px; text-align: end;">

          <a class="btn btn-primary1" id="btn-departamento-guardar" onclick="guardar()">Guardar</a>
        </div>

      </div>
    </div>

  </div>



</div>



<?php //fin  Modal departamento*/?>

<?php //Modal Configuracion */?>

<div id="miModal1" class="modal" style=" z-index: 101;">
  <div class="modal-contenido">

    <div class="row"
      style="background-color: #0c4dc1;width: 100%;margin-left: 0px !important;margin-right: 0px !important;height:70px">
      <div class="col-xs-6" style="color: white;">
        <h2>Gestionar cargo</h2>
      </div>

      <div class="col-xs-6" style="text-align: end;top: 10px;margin-top: 17px;padding-right: 29px;">
        <a href="#" style="text-decoration: none;color: white;">X</a>
      </div>
    </div>

    <div class="row start-xs" style="margin-top: 40px;padding-left: 95px;padding-right: 95px;">


      <div class="col-xs-4" style="margin-top: 25px;">
        <!--Select with pure css-->
        <div class="select">
          <select class="select-text" required id="select-cargo-departamento">
            <option value="" disabled selected></option>
            <?php foreach ($this->departamento as $value) { ?>
            <option value="<?= $value["id"] ?>"><?= $value["nombre"] ?></option>
            <?php } ?>
          </select>
          <label class="select-label">Departamento</label>
        </div>
        <!--Select with pure css-->
      </div>

      <div class="col-xs-4" style="margin-top: 25px;">
        <div class="omrs-input-group">
          <label class="omrs-input-filled">
            <input type="text" onkeypress="return soloLetras(event)" required id="input-cargo-nombre"
              style="background-color: white;   height: 50px;margin-top: -8px;">
            <span class="omrs-input-label">Cargo</span>
          </label>
        </div>
      </div>


      <div class="col-xs-4" style="margin-top: 25px;">
        <div class="omrs-input-group">
          <label class="omrs-input-filled">
            <input type="text" onkeypress="return numeros(event)" required id="input-cargo-salario"
              style="background-color: white;   height: 50px;margin-top: -8px;">
            <span class="omrs-input-label">Salario</span>
          </label>
        </div>
      </div>


      <div class="col-xs-12">
        <div class="btn-group">
          <div style=" margin-top: 25px; text-align: end;">
            <a class="btn btn-primary1" onclick="guardarCargo()">Guardar</a>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>




<div id="miModal2w2" class="modal" style=" z-index: 102;">
  <div class="modal-contenido">

    <div class="row"
      style="background-color: #0c4dc1;width: 100%;margin-left: 0px !important;margin-right: 0px !important;height:70px">
      <div class="col-xs-6" style="color: white;">
        <h2>Editar cargo</h2>
      </div>

      <div class="col-xs-6" style="text-align: end;top: 10px;margin-top: 17px;padding-right: 29px;">
        <a href="#" style="text-decoration: none;color: white;">X</a>
      </div>
    </div>

    <div class="row start-xs" style="margin-top: 40px;padding-left: 95px;padding-right: 95px;">


      <div class="col-xs-12 col-sm-6" style="margin-top: 25px;">
        <!--Select with pure css-->
        <div class="select">
          <select class="select-text" required id="select-cargo-departasmento">
            <option value="" disabled selected></option>
            <?php foreach ($this->departamento as $value) { ?>
            <option value="<?= $value["id"] ?>"><?= $value["nombre"] ?></option>
            <?php } ?>
          </select>
          <label class="select-label">Departamento</label>
        </div>
        <!--Select with pure css-->
      </div>

      <div class="col-xs-12 col-sm-6" style="margin-top: 25px;">
        <!--Select with pure css-->
        <div class="select">
          <select class="select-text" required id="select-cargo-deparstamento">
            <option value="" disabled selected></option>
            <?php foreach ($this->departamento as $value) { ?>
            <option value="<?= $value["id"] ?>"><?= $value["nombre"] ?></option>
            <?php } ?>
          </select>
          <label class="select-label">Departamento</label>
        </div>
        <!--Select with pure css-->
      </div>


      <div class="col-xs-12 col-sm-6" style="margin-top: 25px;">
        <div class="omrs-input-group">
          <label class="omrs-input-filled">
            <input type="text" onkeypress="return soloLetras(event)" required id="input-casrgo-nombre"
              style="background-color: white;   height: 50px;margin-top: -8px;">
            <span class="omrs-input-label">Cargo</span>
          </label>
        </div>
      </div>


      <div class="col-xs-4  col-sm-6" style="margin-top: 25px;">
        <div class="omrs-input-group">
          <label class="omrs-input-filled">
            <input type="text" onkeypress="return numeros(event)" required id="input-cargso-salario"
              style="background-color: white;   height: 50px;margin-top: -8px;">
            <span class="omrs-input-label">Salario</span>
          </label>
        </div>
      </div>


      <div class="col-xs-12">
        <div class="btn-group">
          <div style=" margin-top: 25px; text-align: end;">

            <a class="btn btn-primary1" onclick="guardarCargo()">Guardar</a>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>




<?php //Modal Configuracion*/?>
<?php include (getcwd()."/layout/BottomComponent.phtml")?>

<script src='<?=$this->base_url ?>/assets/js/sweetalert2@10.js'></script>


<script>
function soloLetras(e) {
  var key = e.keyCode || e.which,
    tecla = String.fromCharCode(key).toLowerCase(),
    letras = " áéíóúabcdefghijklmnñopqrstuvwxyz",
    especiales = [8, 37, 39, 46],
    tecla_especial = false;

  for (var i in especiales) {
    if (key == especiales[i]) {
      tecla_especial = true;
      break;
    }
  }

  if (letras.indexOf(tecla) == -1 && !tecla_especial) {
    return false;
  }
}

function numeros(e) {
  key = e.keyCode || e.which;
  tecla = String.fromCharCode(key).toLowerCase();
  letras = " 0123456789";
  especiales = [8, 37, 39, 46];

  tecla_especial = false
  for (var i in especiales) {
    if (key == especiales[i]) {
      tecla_especial = true;
      break;
    }
  }

  if (letras.indexOf(tecla) == -1 && !tecla_especial)
    return false;
}


function editardepartamento(id, nombre) {
  var dept = document.getElementById("input-departamento-nombre");
  var deptId = document.getElementById("input-departamento-id");
  deptId.value = id
  dept.value = nombre;



  window.location.href = "#miModal";
}



function guardar() {
  var dept = document.getElementById("input-departamento-nombre");
  var deptId = document.getElementById("input-departamento-id");

  var formData = {
    id: deptId.value || undefined,
    nombre: dept.value
  }


  $.ajax({
      method: "POST",
      url: "<?=$this->base_url ?>/configuracion/guardarDepartamento",
      data: formData
    })
    .done(function(msg) {

      Swal.fire(
        'Exito!',
        'Registro guardado',
        'success'
      ).then((result) => {
        cerrarModal()
      });


    })
    .fail(function(response) {
      alert("error interno");
    });

}

function cerrarModal() {
  window.location.href = "#";
  location.reload();
}



function guardarCargo() {
  var dept = document.getElementById("select-cargo-departamento");
  var salario = document.getElementById("input-cargo-salario");
  var nombre = document.getElementById("input-cargo-nombre");

  var formData = {
    id: undefined,
    nombre: nombre.value,
    salario_base: salario.value,
    departamento_id: dept.value
  }


  $.ajax({
      method: "POST",
      url: "<?=$this->base_url ?>/configuracion/guardarCargo",
      data: formData
    })
    .done(function(msg) {

      Swal.fire(
        'Exito!',
        'Registro guardado',
        'success'
      ).then((result) => {
        cerrarModal()
      });


    })
    .fail(function(response) {
      alert("error interno");
    });
}

function cerrarModal3() {
  window.location.href = "#";
  location.reload();
}

function editarCargo(id, e) {
  e.preventDefault();
  console.log("ok")

  //$("#miModal2w2").css("opacity", 1)

  window.location.href = "#miModal2w2";
}
</script>