<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/modalUser.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/user.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<script src='<?=$this->base_url ?>/assets/js/jquery-3.5.0.min.js' defer ></script>
<script src='<?=$this->base_url ?>/assets/js/ModalFormUser.js' defer ></script>


<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <h1>GESTIONAR USUARIOS </h1>
  </div>
</div>


<div class="row" style="margin-bottom: 20px;">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="card" Id="Card-User1" style="">

      <div class="card-body">

        <div class="row start-xs">
          <div class="col-xs-3">
            <i class="fas fa-id-badge" style="font-size: 167px;color: white;"></i>
          </div>
          <div class="col-xs-3">
            <h1 class="card-title" id="CardTitle" style="color:white">
              <?php   
                $activos = 0;
                $desactivado = 0;
                foreach ($this->usuarios as $value) {
                  if ($value['status'] == "t") {
                    $activos = $activos + 1;
                  }else{
                    $desactivado = $desactivado + 1;
                  }
                }       
                  echo $activos;
              ?>
            </h1>
          </div>

          <div class="col-xs-6">
            <h1 class="card-title" id="CardTitle1" style="color:white">Usuarios Admitidos </h1>
            <p class="card-text" id="CardText1">Aqui usuarios que pueden hacer uso del sistema</p>
          </div>

        </div>

        <div style="text-align: end;"> <a id="ai" href="#" class="btn btn-primary">Admitir</a></div>
      </div>
    </div>
  </div>


  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="card" Id="Card-User2" style="">

      <div class="card-body">

        <div class="row start-xs">
          <div class="col-xs-3">
            <i class="fas fa-id-badge fa-10x" style="color: white;"></i>
          </div>
          <div class="col-xs-3">

            <h1 class="card-title" id="CardTitle" style="color:white"><?php echo $desactivado;?> </h1>
          </div>

          <div class="col-xs-6">
            <h1 class="card-title" id="CardTitle1">Usuarios Bloqueados </h1>
            <p class="card-text" id="CardText1">Aqui usuarios con restriccion de acceso</p>
          </div>

        </div>


        <div style="text-align: end;"> <a id="ai" href="#" class="btn btn-primary">Bloquear</a></div>
      </div>
    </div>
  </div>

</div>


<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

    <div class="card" style="padding: 2%;">
      <div class="card-body">
        <div class="row start-xs">
          <div class="col-xs-6">
            <input type="search" id="InputUser" onkeyup=" UserFunction()" placeholder="Buscar Usuarios"
              title="Busca Usuarios">
          </div>
        </div>
      </div>      
      
      <table id="Table-User">
        <tr class="header" style="background-color: black;color: #fbfbfb;">
          <th >ID_Usuario</th>
          <th >Nombre</th>
          <th >Apellido</th>
          <th >Usuario</th>
          <th >Status</th>
          <th >Tipo</th>
          <th >Acciones</th>
        </tr>
      <?php
    
        foreach ($this->usuarios as $value) {    
          
      ?>
          <tr>
            <td><?=$value['id_usuario']?></td>
            <td><?=$value['nombre_usuario']?></td>
            <td><?=$value['apellido_usuario']?></td>
            <td><?=$value['usuario']?></td>
            <td><?=($value['status'] == "t") ? 'Activo' : 'Desactivado';?></td>
            <td><?=$value['nombre_tipo_usuario']?></td>
            <td>
              <button class='circle-right-btn' id="Editar" type='submit'><i class='fas fa-edit'> </i></button>
            </td>
            <td>
              <button class='circle-right-btn' id="Delete" type='submit'><i class='fas fa-trash'> </i></button>
            </td>
          </tr>
        <?php
        }
      ?>

      </table>

      <div class="row center-xs">
        <div class="col-xs
          <div style="text-align: center; margin-top: 25px;"> <a id="ai" href="#miModal" class="btn btn-primary">Agregar</a>
          </div>
          
        </div>

      </div>


 <div id="miModal" class="modal">

    <div class="modal-contenido" style="border-radius: 0.6rem;" >
      <div class="row" style="background-color: #0c4dc1;width: 100%;margin-left: 0px !important; margin-right: 0px !important;">
        <div class="col-xs-8" style="color: white;">
          <h2>Agregar Usuario</h2>
        </div>
        <div class="col-xs-4" style="text-align: end;top: 10px;margin-top: 17px;padding-right: 29px;">

          <a href="#"class="modal-close" style="text-decoration: none;color: white;">&times;</a>
        </div>

      </div>


      <div id="formUser">
        <form>
          <div class="row start-xs" >

            <div class="col-xs-4">
            <input type="text" style="width: 100%;" id="InputUser" placeholder="Nombres" >
            </div> 

            <div class="col-xs-4">
              <input type="text" style="width: 100%;" id="InputUser" placeholder="Apellido" >
            </div> 

            <div class="col-xs-4">
              <input type="text" style="width: 100%;"  id="InputUser" placeholder="Cedula"  >
            </div> 

            <div class="col-xs-4" >
              <input type="text" style="width: 100%;"  id="InputUser" placeholder="Usuario" >
            </div> 

            <div class="col-xs-4" >
              <input type="password" style="width: 100%;" id="InputUser" placeholder="Contaseña" >
            </div> 

            <div class="col-xs-4" >
              <input type="text" style="width: 100%;" id="InputUser" placeholder="Confirmar contraseña">
            </div> 

                
            <div class="col-xs-4" >  
              <div class="select" >

                <label for= "status" style="font-size: 20px;">Estado</label>
                <select class="form-control" id="InputUser" required>

                  <option selected> Seleccione </option> 
                  <option value="1"> Admitivo </option> 
                  <option value="2"> Bloqueado </option>            

                </select>

              </div>
            </div>

            <div class="col-xs-4" >  
              <div class="select" >

                <label for= "Rol" style="font-size: 20px;">Rol</label>
                <select class="form-control" id="InputUser" required>
                    
                  <option selected> Seleccione </option> 
                  <option value="1"> Administrador </option> 
                  <option value="2"> Usuario </option>            

                </select>

              </div>
            </div>
            
            <div class="col-xs-4" >  
              <div class="select" >

                <label for= "Tipo usuario" style="font-size: 20px;">Tipo de Usuario</label>
                <select class="form-control" id="InputUser" required>
                    
                  <option selected> Seleccione </option> 
                  <option value="1"> Administrador </option> 
                  <option value="2"> Usuario </option>            

                </select>

              </div>
            </div>

            <div class="col-xs-12" style="text-align: center; margin-top: 25px;" >
              <button class="btn btn-primary" type="submit"  > <i class="fa fa-fw fa-lg fa-check-circle"></i>Registrar 
              </button>
            </div>

          </div> 
       </form>   
      </div>

  </div>

</div>
</div>


<script>
function UserFunction() {
  var input, filter, table, tr, td, i, txtValue;
  input = document.getElementBy("InputUser");
  filter = input.value.toUpperCase();
  table = document.getElementById("Table-User");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      txtValue = td.textContent || td.innerText;
      if (txtValue.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

<?php include (getcwd()."/layout/BottomComponent.phtml")?>






<!-- 
      <div id="formUser">
        <form method="POST">

          <input class="form-control" type="text" id="InputUser" placeholder="Nombres" required>

          <input type="text" id="InputUser" placeholder="Apellido" required>


          <input type="text" id="InputUser" placeholder="Cedula" required>

        
          <input type="text" id="InputUser" placeholder="Usuario" required>


          <input type="password" id="InputUser" placeholder="Contraseña" required>


          <input type="password" id="InputUser" placeholder="Confirmar Contraseña" required>

          <div></div>
          
          <label for= "status">Estado</label>
          <select class="form-control" id="InputUser" required>

            <option selected> Seleccione </option> 
            <option value="1"> Admitivo </option> 
            <option value="2"> Bloqueado </option>            

          </select>
          
                    
          <label for= "Rol">Rol</label>
          <select class="form-control" id="InputUser" required>
            
            <option selected> Seleccione </option> 
            <option value="1"> Administrador </option> 
            <option value="2"> Usuario </option>            

          </select>
          
          <div></div>
          
          <label for= "Tipo usuario">Tipo de Usuario</label>
          <select class="form-control" id="InputUser" required>
            
            <option selected> Seleccione </option> 
            <option value="1"> Administrador </option> 
            <option value="2"> Usuario </option>            

          </select>
           -->