<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>

<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/funcionario.css">

<h1 class="h1">Gestionar Funcionario</h1>

<div class="row center-xs">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">Card title</h1>
<p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">Card title</h1>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
</div>






<div class="card" style="border-bottom-color: white; margin-top:15px;">
    <div class="card-body" >
      <div class="row">

         <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
          <select class="select-css">
           <option>Seleccionar...</option>
           <option>Primera opción</option>
           <option>Segunda opción</option>
           <option>Tercera opción</option>
           <option>Cuarta opción</option>
          </select>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
          <select class="select-css">
           <option>Seleccionar...</option>
           <option>Primera opción</option>
           <option>Segunda opción</option>
          <option>Tercera opción</option>
           <option>Cuarta opción</option>
          </select>
        </div>

      <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
      
      
		<form class="form">
			<input type="email" class="form__field" placeholder="Your E-Mail Address" />
			<button type="button" class="btn btn--primary btn--inside uppercase">Send</button>
		</form>

      </div>

      <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
      
        <button type="button" class="btn btn-primary btn-busqueda "> <i class="fa fa-search" style="font-size:20px;"></i></button>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-2 col-lg-2">
      <a href="#" class="myButton"> <i class="fa fa-plus-circle"  style="font-size:20px;"></i></i></a>
   
  </button>
      </div>

    </div>
    
  </div>
</div>

<div class="card2" style=" background-color: white; margin-top: -2px;
    border-top-color: white;">
      <div class="card-body">
       
      <table id="customers">
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>Alfreds Futterkiste</td>
    <td>Maria Anders</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Berglunds snabbköp</td>
    <td>Christina Berglund</td>
    <td>Sweden</td>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
  <tr>
    <td>Ernst Handel</td>
    <td>Roland Mendel</td>
    <td>Austria</td>
  </tr>
  <tr>
    <td>Island Trading</td>
    <td>Helen Bennett</td>
    <td>UK</td>
  </tr>
  <tr>
    <td>Königlich Essen</td>
    <td>Philip Cramer</td>
    <td>Germany</td>
  </tr>
  <tr>
    <td>Laughing Bacchus Winecellars</td>
    <td>Yoshi Tannamuri</td>
    <td>Canada</td>
  </tr>
  <tr>
    <td>Magazzini Alimentari Riuniti</td>
    <td>Giovanni Rovelli</td>
    <td>Italy</td>
  </tr>
  <tr>
    <td>North/South</td>
    <td>Simon Crowther</td>
    <td>UK</td>
  </tr>
  <tr>
    <td>Paris spécialités</td>
    <td>Marie Bertrand</td>
    <td>France</td>
  </tr>
</table>

      </div>
</div>
<?php include (getcwd()."/layout/BottomComponent.phtml")?>

