<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/main.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/modal.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/funcionario.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/tableBoss.css">



<script src='<?=$this->base_url ?>/assets/js/popper_core@2.js'></script>
<script src='<?=$this->base_url ?>/assets/js/tippy@6.js'></script>
<script src='<?=$this->base_url ?>/assets/js/jquery-3.5.1.min.js'></script>
<script src='<?=$this->base_url ?>/assets/js/sweetalert2@10.js'></script>


<script src='<?=$this->base_url ?>/assets/js/dateTable.js'></script>
<script src='<?=$this->base_url ?>/assets/js/dateTableBoss.js'></script>
<h1 class="h1">Gestionar Funcionario</h1>


<div class="card2" style=" background-color: white; margin-top: -2px;
    border-top-color: white;">
  <div class="card-body">

    <table id="example" class="stripe" style="width:100%" style="margin-top: 40px;">
      <thead>

        <tr>
          <th>Cedula</th>
          <th>Nombres</th>
          <th>Apellidos</th>
          <th>Direccion</th>
          <th>Telefono</th>
          <th>Departamento</th>
          <th>Cargo</th>
          <th>Accion</th>
        </tr>
      </thead>
      <tbody>

        <?php foreach($this->funcionario as $valor) {?>
        <tr>
          <td><?= $valor["cedula"]?></td>
          <td><?= "{$valor["primer_nombre"]} {$valor["segundo_nombre"]}"?></td>
          <td><?= $valor["primer_apellido"]?><?= $valor["segundo_apellido"]?></td>
          <td><?= $valor["direccion"]?></td>
          <td><?= $valor["telefono"]?></td>
          <td><?= $valor["departamento_nombre"]?></td>
          <td><?= $valor["cargo_nombre"]?></td>

          <td style=" text-align: center;">



            <button class="circle-right-btn" type="button" onclick="editarFuncionarioRequest(<?= $valor["id"] ?>)">
              <i class="fas fa-user-edit" style="font-size: 32px;"></i></a>
            </button>



          </td>
        </tr>
        <?php } ?>



      </tbody>

    </table>



  </div>
  <div class="col-xs-12">
    <div style="text-align:center">
      <a href="#miModal" id="detalle" class="btn btn-primary"> Agregar</a>
    </div>
  </div>

</div>


</div>


<!--Inicio Modal Funcionario-->
<div id="miModal" class="modal">

  <div class="modal-contenido">

    <div class="row"
      style="background-color: #0c4dc1;width: 100%;margin-left: 0px !important;margin-right: 0px !important;height:70px">
      <div class="col-xs-6" style="color: white;">
        <h2>Gestionar Funcionario</h2>
      </div>

      <div class="col-xs-6" style="text-align: end;top: 10px;margin-top: 17px;padding-right: 29px;">
        <button type="button" onclick="cerrarModal()" style="
          height: 30px;
          width: 30px;
          border-radius: 50px;
          border: none;
          background: #0000ff00;
          color: white;
          cursor: pointer;">X</button>
      </div>
    </div>


    <input type="hidden" id="id" />
    <div class="row start-xs" id="form" style="margin-top: 40px;padding-left: 95px;padding-right: 95px;">

      <div class="col-xs-4">
        <!--Input css-->
        <span class="input input--yoshiko">
          <input class="input__field input__field--yoshiko" type="text" name="cedula" id="cedula" />
          <label class="input__label input__label--yoshiko" for="input-10">
            <span class="input__label-content input__label-content--yoshiko" data-content="Cedula">Cedula</span>
          </label>
        </span>
        <!--Input css-->
      </div>
      <div class="col-xs-4">
        <!--Input css-->
        <span class="input input--yoshiko">
          <input class="input__field input__field--yoshiko" type="text" id="nombrep" />
          <label class="input__label input__label--yoshiko" for="input-10">
            <span class="input__label-content input__label-content--yoshiko" data-content="Primer Nombre">Primer
              Nombre</span>
          </label>
        </span>
        <!--Input css-->
      </div>

      <div class="col-xs-4">
        <!--Input css-->
        <span class="input input--yoshiko">
          <input class="input__field input__field--yoshiko" type="text" id="nombres" />
          <label class="input__label input__label--yoshiko" for="input-10">
            <span class="input__label-content input__label-content--yoshiko" data-content="Segundo Nombre">Segundo
              Nombre</span>
          </label>
        </span>
        <!--Input css-->
      </div>

      <div class="col-xs-4">
        <!--Input css-->
        <span class="input input--yoshiko">
          <input class="input__field input__field--yoshiko" type="text" id="apellidop" />
          <label class="input__label input__label--yoshiko" for="input-10">
            <span class="input__label-content input__label-content--yoshiko" data-content="Primer Apellido">Primer
              Apellido</span>
          </label>
        </span>
        <!--Input css-->
      </div>

      <div class="col-xs-4">
        <!--Input css-->
        <span class="input input--yoshiko">
          <input class="input__field input__field--yoshiko" type="text" id="apellidos" />
          <label class="input__label input__label--yoshiko" for="input-10">
            <span class="input__label-content input__label-content--yoshiko" data-content="Segundo Apellido">Segundos
              Apellido</span>
          </label>
        </span>
        <!--Input css-->
      </div>
      <div class="col-xs-4">
        <!--Input css-->
        <span class="input input--yoshiko">
          <input class="input__field input__field--yoshiko" type="text" id="telefono" />
          <label class="input__label input__label--yoshiko" for="input-10">
            <span class="input__label-content input__label-content--yoshiko" data-content="Telefono">Telefono</span>
          </label>
        </span>
        <!--Input css-->
      </div>
      <div class="col-xs-4">
        <!--Input css-->
        <span class="input input--yoshiko">
          <input class="input__field input__field--yoshiko" type="text" id="direccion" />
          <label class="input__label input__label--yoshiko" for="input-10">
            <span class="input__label-content input__label-content--yoshiko" data-content="Direccion">Direccion</span>
          </label>
        </span>
        <!--Input css-->
      </div>
      <div class="col-xs-4">
        <!--Select with pure css-->
        <div class="select">
          <select class="select-text" id="departamento" required onchange="obtenerlistaDeCargosPorDepartamento(this)">
            <option value="" disabled selected> Departamento </option>
            <?php foreach ($this->departamento as $value) { ?>
            <option value="<?= $value["id"] ?>"><?= $value["nombre"] ?></option>
            <?php } ?>
          </select>
          <label class="select-label">Departamento</label>
        </div>
        <!--Select with pure css-->

      </div>
      <div class="col-xs-4">
        <!--Select with pure css-->
        <div class="select">
          <select class="select-text" required id="cargo">
            <option value="" disabled selected> Cargo </option>
          </select>
          <label class="select-label">Cargo</label>
        </div>
        <!--Select with pure css-->

      </div>


      <div class="col-xs-12">
        <div class="btn-group">

          <button type="button" onclick="agregar()" class="btn btn-primary1">Guardar</button>
        </div>
      </div>
    </div>

  </div>
</div>


<?php include (getcwd()."/layout/BottomComponent.phtml")?>

<script>
//aquiquede 
function agregar() {
  var input_cedula = document.getElementById("cedula");
  var input_nombrep = document.getElementById("nombrep");
  var input_nombres = document.getElementById("nombres");
  var input_apellidop = document.getElementById("apellidop");
  var input_apellidos = document.getElementById("apellidos");
  var input_telefono = document.getElementById("telefono");
  var input_direccion = document.getElementById("direccion");
  var input_cargo = document.getElementById("cargo");
  var input_id = document.getElementById("id");

  var dataToSend = {
    id: input_id.value || undefined,
    cedula: input_cedula.value,
    nombrep: input_nombrep.value,
    nombres: input_nombres.value,
    apellidop: input_apellidop.value,
    apellidos: input_apellidos.value,
    telefono: input_telefono.value,
    direccion: input_direccion.value,
    cargo: input_cargo.value,
  };

  console.log(dataToSend)


  $.ajax({
      method: "POST",
      url: "<?=$this->base_url ?>/funcionario/guardar",
      data: dataToSend
    })
    .done(function(msg) {

      Swal.fire(
        'Exito!',
        'Registro guardado',
        'success'
      ).then((result) => {
        cerrarModal()
      });

    })
    .fail(function(response) {
      alert("error interno");
    });
}

$(document).ready(function() {
  $('#example').DataTable();
  tippy('#ai', {
    content: 'Modificar Funcionario',
  });
});


function cerrarModal() {
  window.location.href = "#";
  location.reload();
}


function obtenerlistaDeCargosPorDepartamento(elemnt) {

  request_obtenerlistaDeCargosPorDepartamento(elemnt.value);
}


function request_obtenerlistaDeCargosPorDepartamento(departamento) {
  var dataToSend = {
    departamento: departamento
  }

  $.ajax({
      method: "POST",
      url: "<?=$this->base_url ?>/funcionario/obtnerCargoPorDepartamento",
      data: dataToSend
    })
    .done(function(msg) {
      var cargo = document.getElementById("cargo")
      cargo.innerHTML = "";

      var opt = document.createElement('option');
      opt.value = "";
      opt.innerHTML = "seleccione un cargo";
      var att = document.createAttribute("disabled");
      opt.setAttributeNode(att);
      cargo.appendChild(opt);


      if (msg) {
        msg.forEach(function(v) {
          var opt = document.createElement('option');
          opt.value = v.id;
          opt.innerHTML = v.nombre;
          cargo.appendChild(opt);
        })
      }

      console.log(msg)

    })
    .fail(function(response) {
      alert("error interno");
    });
}



function editarFuncionarioRequest(id) {

  $.ajax({
      method: "POST",
      url: "<?=$this->base_url ?>/funcionario/obtnerUnoPorId",
      data: {
        id
      }
    })
    .done(function(msg) {

      request_obtenerlistaDeCargosPorDepartamento(msg.departamento_id)

      var input_id = document.getElementById("id");
      var input_cedula = document.getElementById("cedula");
      var input_nombrep = document.getElementById("nombrep");
      var input_nombres = document.getElementById("nombres");
      var input_apellidop = document.getElementById("apellidop");
      var input_apellidos = document.getElementById("apellidos");
      var input_telefono = document.getElementById("telefono");
      var input_direccion = document.getElementById("direccion");



      input_id.value = msg.id;
      input_cedula.value = msg.cedula;
      input_nombrep.value = msg.primer_nombre;
      input_nombres.value = msg.segundo_nombre;
      input_apellidop.value = msg.primer_apellido;
      input_apellidos.value = msg.segundo_apellido;
      input_telefono.value = msg.telefono;
      input_direccion.value = msg.direccion;


      $(`#departamento option[value='${msg.departamento_id}']`).prop('selected', true);
      $(`#cargo option[value='${msg.cargo_id}']`).prop('selected', true);


      console.log(msg)

      window.location.href = "#miModal";

    })
    .fail(function(response) {
      alert("error interno");
    });

}
</script>