<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>

<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/funcionario.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/responsive.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/w3.css">
<link href='https://fonts.googleapis.com/css?family=Wire+One|Raleway:300' rel='stylesheet' type='text/css'>

<script src='<?=$this->base_url ?>/assets/js/dataTables.responsive.min.js'></script>
<script src='<?=$this->base_url ?>/assets/js/jquery-3.5.1.js'></script>
<script src='<?=$this->base_url ?>/assets/js/jquery.dataTables.min.js'></script>


<h1 class="h1">Gestionar Funcionario</h1>

<div class="row center-xs">

  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="carta1">
      <div class="card-body">
        <div class="row">
          <div class="col-xs-4">
            <div class="box">100</div>
          </div>

          <div class="col-xs-8">
            <h3 class="card-title">Funcionarios Activos</h3>
            <hr class="solid" style="margin-top:-10px;">
            <p class="card-text">Muestra un registro de los funcionarios que actualmente se encuantran laborado.
            </p>

          </div>
        </div>

        <div class="row end-xs">
          <div class="col-xs-12">
            <a class="btn btn-primary1">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="carta2">
      <div class="card-body">
        <div class="row">
          <div class="col-xs-4">
            <div class="box">100</div>
          </div>

          <div class="col-xs-8">
            <h3 class="card-title">Funcionarios Inactivos</h3>
            <hr class="solid" style="margin-top:-10px;">
            <p class="card-text">Muestra un registro de los funcionarios que no se encuentran
              laborando sea por retiro o permiso. </p>

          </div>
        </div>

        <div class="row end-xs">
          <div class="col-xs-12">
            <a class="btn btn-primary1">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>






<div class="card" style="border-bottom-color: white; margin-top:15px;">
  <div class="card-body">
    <div class="row">

      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <select class="select-css">
          <option>Seleccionar...</option>
          <option>Primera opción</option>
          <option>Segunda opción</option>
          <option>Tercera opción</option>
          <option>Cuarta opción</option>
        </select>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <select class="select-css">
          <option>Seleccionar...</option>
          <option>Primera opción</option>
          <option>Segunda opción</option>
          <option>Tercera opción</option>
          <option>Cuarta opción</option>
        </select>
      </div>
    </div>

    <div class="card2" style=" background-color: white; margin-top: -2px;
    border-top-color: white;">
      <div class="card-body">

        <table id="example" class="display nowrap" style="width:100%">
          <thead style="background-color: #0a5eff;
color: white;">
            <tr>
              <th>First name</th>
              <th>Last name</th>
              <th>Position</th>
              <th>Office</th>
              <th>Age</th>
              <th>Start date</th>
              <th>Salary</th>
              <th>Extn.</th>

            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Tiger</td>
              <td>Nixon</td>
              <td>System Architect</td>
              <td>Edinburgh</td>
              <td>61</td>
              <td>2011/04/25</td>
              <td>$320,800</td>
              <td>5421</td>

            </tr>
            <tr>
              <td>Garrett</td>
              <td>Winters</td>
              <td>Accountant</td>
              <td>Tokyo</td>
              <td>63</td>
              <td>2011/07/25</td>
              <td>$170,750</td>
              <td>8422</td>

            </tr>
            <tr>
              <td>Ashton</td>
              <td>Cox</td>
              <td>Junior Technical Author</td>
              <td>San Francisco</td>
              <td>66</td>
              <td>2009/01/12</td>
              <td>$86,000</td>
              <td>1562</td>

            </tr>
            <tr>
              <td>Cedric</td>
              <td>Kelly</td>
              <td>Senior Javascript Developer</td>
              <td>Edinburgh</td>
              <td>22</td>
              <td>2012/03/29</td>
              <td>$433,060</td>
              <td>6224</td>

            </tr>
            <tr>
              <td>Cedric</td>
              <td>Kelly</td>
              <td>Senior Javascript Developer</td>
              <td>Edinburgh</td>
              <td>22</td>
              <td>2012/03/29</td>
              <td>$433,060</td>
              <td>6224</td>

            </tr>
            <tr>
              <td>Cedric</td>
              <td>Kelly</td>
              <td>Senior Javascript Developer</td>
              <td>Edinburgh</td>
              <td>22</td>
              <td>2012/03/29</td>
              <td>$433,060</td>
              <td>6224</td>

            </tr>

          </tbody>
        </table>



      </div>
    </div>



    <div class="row center-xs">

      <div class="col-xs-2 col-sm-2 col-md-1 col-lg-1" style="margin-left: -3px;
margin-right: -39px;">
        <button onclick="document.getElementById('id01').style.display='block'" class="w3-button1 w3-black"><i
            class="fa fa-plus" aria-hidden="true"></i>
          Add</button>
      </div>
      <!--Inicio modal add-->

      <div id="id01" class="w3-modal">
        <div class="w3-modal-content w3-animate-top w3-card-4">
          <header class="w3-container w3-teal">
            <span onclick="document.getElementById('id01').style.display='none'"
              class="w3-button w3-display-topright">&times;</span>
            <h2>Agregar Funcionario</h2>
          </header>
          <div class="w3-container">
            <!-- Primera columna Modal  -->
            <div class="row center-xs" style="margin-top: 10px;">

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Cedula" require />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Primer Nombre" />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">

                <input type="text" class="mo" placeholder="Segundo Nombre" />
              </div>
              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Primer Apellido" />
              </div>

            </div>
            <!-- Segunda columna Modal  -->
            <div class="row center-xs" style="margin-top: 10px;">



              <div class="col-xs-12 col-sm-8 col-md-6">
                <input type="text" class="mo" placeholder="Segundo Apellido " />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6">
                <input type="text" class="mo" placeholder="Telefono" />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <select class="select-css" style=" width: 100%;
;">
                  <option>Cargo...</option>
                  <option>Primera opción</option>
                  <option>Segunda opción</option>
                  <option>Tercera opción</option>
                  <option>Cuarta opción</option>
                </select>
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Fecha de Nacimiento" />
              </div>


            </div>

            <!-- Tercera Columna Modal  -->
            <div class="row center-xs" style="margin-top: 10px;">

              <div class="col-xs-12 col-sm-8 col-md-6">
                <select class="select-css" style=" width: 100%;">
                  <option>Departamento...</option>
                  <option>Primera opción</option>
                  <option>Segunda opción</option>
                  <option>Tercera opción</option>
                  <option>Cuarta opción</option>
                </select>
              </div>
              <div class="col-xs-12 col-sm-8 col-md-6">
                <input type="text" class="mo" placeholder="Email" />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Fecha Ingreso" />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Edad" />
              </div>
            </div>

            <!-- Cuarta Columna Modal  -->
            <div class="row center-xs" style="margin-top: 10px;">

              <div class="col-xs-12 col-sm-12 col-md-12">
                <input type="text" class="mo" placeholder="Direccion" style="height: 69px;" />
              </div>
            </div>

            <div class="row end-xs" style="margin-top: 10px; margin-bottom:10px;">
              <div class="col-xs-6">

                <button class="button" style="background-color: #1c2f95 !important;">Guardar</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--fin modal add-->




      <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <button onclick="document.getElementById('id02').style.display='block'" class="w3-button1 w3-black"><i
            class="fa fa-pencil-square-o" aria-hidden="true"></i>
          Edit</button>
      </div>
      <!-- Modal Modificar-->

      <div id="id02" class="w3-modal">
        <div class="w3-modal-content w3-animate-top w3-card-4">
          <header class="w3-container w3-teal">
            <span onclick="document.getElementById('id02').style.display='none'"
              class="w3-button w3-display-topright">&times;</span>
            <h2>Modificar Funcionario</h2>
          </header>
          <div class="w3-container">
            <!-- Primera columna Modal  -->
            <div class="row center-xs" style="margin-top: 10px;">

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Cedula" require />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Primer Nombre" />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">

                <input type="text" class="mo" placeholder="Segundo Nombre" />
              </div>
              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Primer Apellido" />
              </div>

            </div>
            <!-- Segunda columna Modal  -->
            <div class="row center-xs" style="margin-top: 10px;">



              <div class="col-xs-12 col-sm-8 col-md-6">
                <input type="text" class="mo" placeholder="Segundo Apellido " />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6">
                <input type="text" class="mo" placeholder="Telefono" />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <select class="select-css" style=" width: 100%;
;">
                  <option>Cargo...</option>
                  <option>Primera opción</option>
                  <option>Segunda opción</option>
                  <option>Tercera opción</option>
                  <option>Cuarta opción</option>
                </select>
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Fecha de Nacimiento" />
              </div>


            </div>

            <!-- Tercera Columna Modal  -->
            <div class="row center-xs" style="margin-top: 10px;">

              <div class="col-xs-12 col-sm-8 col-md-6">
                <select class="select-css" style=" width: 100%;">
                  <option>Departamento...</option>
                  <option>Primera opción</option>
                  <option>Segunda opción</option>
                  <option>Tercera opción</option>
                  <option>Cuarta opción</option>
                </select>
              </div>
              <div class="col-xs-12 col-sm-8 col-md-6">
                <input type="text" class="mo" placeholder="Email" />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Fecha Ingreso" />
              </div>

              <div class="col-xs-12 col-sm-8 col-md-6" style="margin-top: inherit;">
                <input type="text" class="mo" placeholder="Edad" />
              </div>
            </div>

            <!-- Cuarta Columna Modal  -->
            <div class="row center-xs" style="margin-top: 10px;">

              <div class="col-xs-12 col-sm-12 col-md-12">
                <input type="text" class="mo" placeholder="Direccion" style="height: 69px;" />
              </div>
            </div>

            <div class="row end-xs" style="margin-top: 10px; margin-bottom:10px;">
              <div class="col-xs-6">

                <button class="button" style="background-color: #1c2f95 !important;">Guardar</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--fin  Modal Modificar-->


      <div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
        <div class="col-xs-2 col-sm-2 col-md-1 col-lg-1">
          <button class="w3-button1 w3-black"><i class="fa fa-ban" aria-hidden="true"></i>
            Block</button>
        </div>



      </div>
    </div>


    <script>
    $(document).ready(function() {
      $('#example').DataTable({
        responsive: true
      });
    });
    </script>
    <?php include (getcwd()."/layout/BottomComponent.phtml")?>