<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/home.css">


<div class="linea">
    
    <h1 class="title">Bienvenidos al Control de Horas Extras </h1>
    </div>


<?php include (getcwd()."/layout/BottomComponent.phtml")?>
