<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">Card title</h1>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <div class="card">
      <div class="card-body">
        <h1 class="card-title">Card title</h1>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>
</div>




<?php include (getcwd()."/layout/BottomComponent.phtml")?>
