<div class="navbar">
  <a href="<?= $this->base_url ?>/home">Inicio</a>


  <div class="dropdown">
    <button class="dropbtn">Quienes somos
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="<?= $this->base_url ?>/misionVision">Mision & Vision </a>
      <a href="<?= $this->base_url ?>/organigrama">Organigrama</a>
    </div>
  </div>

  <div class="dropdown">
    <button class="dropbtn">Horas Extras (coordinador)
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="<?= $this->base_url ?>/HrasExtras/coordinador">Inicio</a>
      <a href="<?= $this->base_url ?>/HrasExtras/coordinador/aprobados">Aprobados</a>
      <a href="<?= $this->base_url ?>/HrasExtras/coordinador/revision">Revision</a>
    </div>
  </div>

  <div class="dropdown">
    <button class="dropbtn">Horas Extras (RRHH)
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="<?= $this->base_url ?>/HrasExtras/rrhh">inicio</a>
    </div>
  </div>

  <div class="dropdown">
    <button class="dropbtn">Usuarios
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="<?= $this->base_url ?>/user">Usuarios</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">Funcionarios
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="<?= $this->base_url ?>/funcionario">Funcionario</a>
      <a href="<?= $this->base_url ?>/configuracion">Configuracion</a>

    </div>
  </div>

  <a href="#" style="float: right">Administrador</a>
</div>