<div class="navbar">
  <a href="<?= $this->base_url ?>/home">Inicio</a>
  <div class="dropdown">
    <button class="dropbtn">Horas Extras
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="<?= $this->base_url ?>/HrasExtras">Inicio</a>
      <a href="<?= $this->base_url ?>/configuracion">Configuracion</a>
      <a href="#">Reportes</a>
    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">Usuarios
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="<?= $this->base_url ?>/user">Usuarios</a>
      <a href="#">Reportes</a>

    </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">Funcionarios
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content">
      <a href="<?= $this->base_url ?>/funcionario">Funcionario</a>
      <a href="#">Reportes</a>
    </div>
  </div>

  <a href="#" style="float: right">Administrador</a>
</div>