<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/modal.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/HrasExtras.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">
<h1 class="h1">Gestionar Horas extras</h1>

<div class="row ">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="card" id="card1">
      <div class="card-body">
        <div class="row start-xs">
          <div class="col-xs-2">
            <i class="far fa-clock fa-7x" style="color:white"></i>

          </div>
          <div class="col-xs-2">
            <h1 class="card-title" style="color: white;font-size: 55px;">100</h1>
          </div>
          <div class="col-xs-8">
            <h1 class="card-title" style="text-align: center;">Horas Aprobadas</h1>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
              content.</p>
          </div>
        </div>
        <div style="text-align:end">
          <a href="#" class="btn btn-primary">Go somewhere</a></div>

      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="card" id="card2">
      <div class="card-body">

        <div class="row start-xs">
          <div class="col-xs-2">
            <i class="fas fa-ban fa-7x" style="color:white"></i>

          </div>


          <div class="col-xs-2">
            <h1 class="card-title" style="color: white;font-size: 55px;">100</h1>
          </div>



          <div class="col-xs-7">
            <h1 class="card-title" style="text-align: center;">Horas Rechazadas</h1>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
              content.</p>
          </div>

        </div>

        <div style="text-align: end;">
          <a href="#" class="btn btn-primary">Go somewhere</a></div>

      </div>
    </div>
  </div>
</div>



<div class="card" style="border-bottom-color: white; margin-top:15px;">
  <div class="card-body">
    <div class="row start-xs">

    <div class="col-xs-4">
            <select id="select" style="width: 100%;">
              <option value=" 0">Filtrar mes:</option>
              <option value="1">Enero</option>
              <option value="2">Febrero</option>
              <option value="3">Marzo</option>
              <option value="4">Abril</option>
              <option value="5">Mayo</option>
              <option value="6">Junio</option>
              <option value="7">Julio</option>
              <option value="8">Agosto</option>
              <option value="9">Septiembre</option>
              <option value="10">Octubre</option>
              <option value="11">Nobiembre</option>
              <option value="12">Diciembre</option>

            </select>
          </div>


          <div class="col-xs-4">
      <input type="text"   id="myInput" onkeyup="myFunction()" placeholder="Buscar cedula" title="Type in a name">
      </div>

      <div class="col-xs-4">
      <div class="boton" style="margin: 0px;margin-left: 88%;"><a href="#" style="font-size: 18px;">
      <i class="fas fa-search" style="margin-top: 4px;margin-left: 4px;"></i></a></div>
      </div>
    </div>
  </div>
</div>










<div class="card2" style=" background-color: white; margin-top: -2px;
    border-top-color: white;">
  <div class="card-body">

    <table id="customers">
      <tr class="header" style="background-color: black;color: #fbfbfb;">
        <th style="width:100%;">Name</th>
        <th style="width:100%;">Country</th>
        <th style="width:100%;">Country</th>
        <th style="width:100%;">State</th>
        <th style="width:100%;">Edit</th>
      </tr>
     
      <tr>
        <td>Berglunds snabbköp</td>
        <td>Christina Berglund</td>
        <td>Sweden</td>
        <td>Germany</td>
        <td> <a  id="ai" href="#miModal1" class="circle-right-btn" type="submit" style="font-size: 15px;margin-left: 20px;"><i class="fas fa-edit fa-2x"> </i></a></td>
      </tr>
  

    </table>

  </div>

</div>


</div>



<div id="miModal1" class="modal">

  <div class="modal-contenido">
    <div class="row" style="background-color: #0c4dc1;width: 100%;margin-left: 0px !important;margin-right: 0px !important;height:70px">
      <div class="col-xs-6" style="color: white;">
        <h2>Modificar Horas Extras</h2>
      </div>

      <div class="col-xs-6" style="text-align: end;top: 10px;margin-top: 17px;padding-right: 29px;">
        <a href="#" style="text-decoration: none;color: white;">X</a>
      </div>
    </div>

    <div class="row center-xs">
      <div class="col-xs-6">  
        <input type="text" id="myInput"  onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">
      </div>

       <div class="col-xs-6">
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">
       </div>
    </div>

  
  </div>
</div>





<?php include (getcwd()."/layout/BottomComponent.phtml")?>