<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>

<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/modal.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/HrasExtras.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/btnGroup.min.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">

<h1 class="h1">Gestionar Horas extras</h1>

<div class="row ">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="card" id="card1">
      <div class="card-body">
        <div class="row start-xs">
          <div class="col-xs-2">
            <i class="far fa-clock fa-7x" style="color:white"></i>

          </div>
          <div class="col-xs-2">
            <h1 class="card-title" style="color: white;font-size: 55px;">100</h1>
          </div>
          <div class="col-xs-8">
            <h1 class="card-title" style="text-align: center;">Horas Aprobadas</h1>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
              content.</p>
          </div>
        </div>
        <div style="text-align:end">
          <a href="#" class="btn btn-primary">Go somewhere</a></div>

      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="card" id="card2">
      <div class="card-body">

        <div class="row start-xs">
          <div class="col-xs-2">
            <i class="fas fa-ban fa-7x" style="color:white"></i>

          </div>


          <div class="col-xs-2">
            <h1 class="card-title" style="color: white;font-size: 55px;">100</h1>
          </div>



          <div class="col-xs-7">
            <h1 class="card-title" style="text-align: center;">Horas en Revisión</h1>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
              content.</p>
          </div>

        </div>

        <div style="text-align: end;">
          <a href="#" class="btn btn-primary">Go somewhere</a></div>

      </div>
    </div>
  </div>
</div>






<div class="card2" style=" background-color: white; margin-top: -2px;
    border-top-color: white;">
  <div class="card-body">

    <table id="customers">
      <tr class="header" style="background-color: black;color: #fbfbfb;">
        <th style="width:30%;">Departamento</th>
        <th style="width: 20%;">Fecha</th>
        <th style="width: 20%;">Total Horas a Pagar Diurnas</th>
        <th style="width: 20%;">Total Horas a Pagar Nocturnas</th>
        <th style="width:30%;">Accion</th>
      </tr>
     
      <tr>
        <td>Sistemas </td>
        <td>12/09/2020</td>
        <td>15:03:0</td>
        <td>08:05:10</td>
        <td> <div class="btn-group">
    <button type="button" class="btn btn-success">Aprobar</button>

    <button type="button" class="btn btn-warning">Posponer</button>
  </div></td>
      </tr>
  

    </table>
    </div>
  </div>
</div>



<div id="miModal1" class="modal">

  <div class="modal-contenido">
    <div class="row" style="background-color: #0c4dc1;width: 100%;margin-left: 0px !important;margin-right: 0px !important;height:70px">
      <div class="col-xs-6" style="color: white;">
        <h2>Modificar Horas Extras</h2>
      </div>

      <div class="col-xs-6" style="text-align: end;top: 10px;margin-top: 17px;padding-right: 29px;">
        <a href="#" style="text-decoration: none;color: white;">X</a>
      </div>
    </div>

    <div class="row center-xs">
      <div class="col-xs-6">  
        <input type="text" id="myInput"  onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">
      </div>

       <div class="col-xs-6">
        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name">
       </div>
    </div>

  
  </div>
</div>





<?php include (getcwd()."/layout/BottomComponent.phtml")?>