<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>

<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/modal.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/HrasExtras.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/tableBoss.css">


<script src='<?=$this->base_url ?>/assets/js/dateTable.js'></script>
<script src='<?=$this->base_url ?>/assets/js/dateTableBoss.js'></script>

<script src='<?=$this->base_url ?>/assets/js/popper_core@2.js'></script>
<script src='<?=$this->base_url ?>/assets/js/tippy@6.js'></script>
<script src='<?=$this->base_url ?>/assets/js/sweetalert2@10.js'></script>

<script>
$(document).ready(function() {
  $('#example').DataTable();
});

$(document).ready(function() {
  tippy('#toolBuscar', {
    content: 'Buscar',
  });
});
$(document).ready(function() {
  tippy('#ai', {
    content: ' pdf',
  });
});
</script>

<h1 class="h1">Gestionar Horas extras</h1>

<div class="row ">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="card" id="card1">
      <div class="card-body">
        <div class="row start-xs">
          <div class="col-xs-2">

            <i class="fas fa-check-double fa-7x" style="color:white"></i>
          </div>

          <div class="col-xs-10" style="color:white">
            <h1 class="card-title" style="text-align: center;">Tiempo restante <?=$this->DiasRestantes?> dias </h1>
            <p id="p" class="card-text">Tiempo restante para finalizar el proceso de gestion de las horas extras para el
              mes de <?=$this->MesActual?>;
            </p>
          </div>
        </div>
        <div style="text-align:end">

        </div>

      </div>
    </div>
  </div>

  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
    <div class="card" id="card2">
      <div class="card-body">

        <div class="row start-xs">
          <div class="col-xs-2">
            <i class="fas fa-clipboard-list fa-7x " style="color:white"></i>

          </div>

          <div class="col-xs-10" style="color:white">
            <h1 class="card-title" style="text-align: center;">Mes <?=$this->MesActual?> <?=$this->EstadoPeriodo?></h1>
            <p id="p" class="card-text">Muestra Estado Actual por mes del proceso de revision de las horas hasta su
              aprobacion </p>
          </div>

        </div>

        <div style="text-align: end;">

        </div>

      </div>
    </div>
  </div>
</div>






<div class="card2" style=" background-color: white; margin-top: -2px; border-top-color: white;">
  <div class="card-body">

    <form action="<?=$this->base_url ?>/HrasExtras/coordinador" method="get">

      <div class="row start-xs">
        <div class="col-xs-4">
          <!--Select with pure css-->
          <div class="select">
            <select class="select-text" required name="anno">
              <option value="" disabled selected></option>

              <?php foreach ($this->annos_existentes as $value) { ?>
              <option value="<?= $value["date_part"] ?>"
                <?= $this->selectValues["anno"] == $value["date_part"] ? "selected" : null ?>><?= $value["date_part"] ?>
              </option>
              <?php } ?>
            </select>
            <label class="select-label">Año</label>
          </div>
          <!--Select with pure css-->
        </div>
        <div class="col-xs-8" style="margin-top: -16PX;margin-bottom: 4px;">
          <button type="submit" id="toolBuscar" class="boton" style="float: right;     float: right;  border: none;
            height: 50px;
            width: 50px;
            color: white;  "><i style="font-size: 26px;" class="fas fa-search"></i></button>
        </div>

      </div>
    </form>



    <hr class="rounded">


    <table id="example" class="stripe" style="width:100%" style="margin-top: 40px;">
      <thead>
        <tr>
          <th>Mes</th>
          <th>año</th>
          <th>Estado por parte de RRHH </th>
          <th width="20%">Acciones</th>
        </tr>
      </thead>
      <tbody>

        <?php foreach ($this->registro_mensual as $value) { ?>
        <tr>
          <td><?= $value["mes"] ?></td>
          <td><?= $value["anno"] ?></td>
          <td><?php
            if(is_null($value["aprobado_rrhh"]) ) {
              echo "por revision";
            }
            elseif($value["aprobado_rrhh"] == "t" ){
              echo "aprobadoo";
            }
            elseif($value["aprobado_rrhh"] == "f" ){
              echo "rechazado";
            }

          ?></td>
          <td style="text-align:center">
            <a href="#miModal" class="circle-right-btn" type="button" onclick="verDetalle('<?= $value["id"] ?>')"
              style="font-size: 15px;margin-left: 20px;color: coral;">
              <i class="fas fa-clipboard" style="font-size: 40px;"></i></a>


            <?php  if($value["aprobado_coordinador"] != "t" ||
                ($value["aprobado_coordinador"] == "t" && $value["aprobado_rrhh"] == "f")
            ) {   ?>
            <a id="btn-aprobar" href="#" onclick='aprobar(<?= $value["id"] ?>, event)' class="circle-right-btn"
              type="button" style="font-size: 15px;margin-left: 20px;color: coral;">
              <i class="fas fa-check" style="font-size: 40px;"></i>
            </a>

            <?php } ?>


          </td>
        </tr>

        <?php } ?>




      </tbody>

    </table>



  </div>
</div>
</div>



<div id="miModal" class="modal">

  <div class="modal-contenido">

    <div class="row"
      style="background-color: #0c4dc1;width: 100%;margin-left: 0px !important;margin-right: 0px !important;height:70px">
      <div class="col-xs-6" style="color: white;">
        <h2>Detalles de Horas Extras</h2>
      </div>


      <div class="col-xs-6" style="text-align: end;top: 10px;margin-top: 17px;padding-right: 29px;">

        <a href="#" style="text-decoration: none;color: white;">X</a>
      </div>
    </div>

    <div class="row start-xs" style="padding-left: 95px;padding-right: 95px;">


      <div id="json"> </div>



      <div class="col-xs-12" style="text-align: end;margin-top: 15px;">
        <a class="circle-right-btn" id="ai" type="button" href="<?=$this->base_url ?>/pdf"
          style="font-size: 15px;margin-left: 20px;color: #d20d0d;" target="_blank">
          <i class="fa fa-file-pdf-o" style="font-size: 40px;"></i></a>
      </div>








    </div>
  </div>


  <?php include (getcwd()."/layout/BottomComponent.phtml")?>

  <script>
  $(document).ready(function() {
    $('#example').DataTable();



    tippy('#toolBuscar', {
      content: 'Buscar',
    });


    tippy('#ai', {
      content: ' Detalles',
    });


    tippy("#btn-aprobar", {
      content: "Aprobar"
    })
  });


  function verDetalle(id) {
    $.ajax({
        method: "get",
        url: "<?=$this->base_url ?>/pdf",
        data: {
          id,
          html: true
        }
      })
      .done(function(msg) {


        $("#json").html(msg)

        $("#ai").attr("href", `<?=$this->base_url ?>/pdf?id=${id}&html=`)



      })
      .fail(function(response) {
        Swal.fire(
          'Error',
          'Algo ha fallado',
          'error'
        );
      });
  }


  function aprobar(id, e) {
    e.preventDefault();
    $.ajax({
        method: "post",
        url: "<?=$this->base_url ?>/HrasExtras/coordinador/aprobarRegistro",
        data: {
          id
        }
      })
      .done(function(msg) {


        console.log(msg);
        location.reload();




      })
      .fail(function(response) {
        Swal.fire(
          'Error',
          'Algo ha fallado',
          'error'
        );
      });

  }
  </script>