<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>

<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/modal.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/HrasExtras.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/reportes.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/tableBoss.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

<script src='<?=$this->base_url ?>/assets/js/dateTable.js'></script>
<script src='<?=$this->base_url ?>/assets/js/dateTableBoss.js'></script>

<script src='<?=$this->base_url ?>/assets/js/popper_core@2.js'></script>
<script src='<?=$this->base_url ?>/assets/js/tippy@6.js'></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<script>
$(document).ready(function() {
  $('#example').DataTable();
});

$(document).ready(function() {
  tippy('#toolDetalles', {
    content: 'Detalles',
  });
});
</script>

<div class="row" style="
    margin-top: -25px;
">
  <div class="col-xs-6">
    <h1 class="h1"> Reportes Coodinador</h1>
  </div>

  <div class="col-xs-6" style="
    text-align: end;
    font-size: 30px;
    margin-top: 23px;
">
    <a href="/SysHorasExtras/HrasExtras" id="salirBtn"> <i class="fas fa-sign-out-alt"></i></a>

  </div>

</div>
</div>


<div class="card2" style=" background-color: white; margin-top: -2px;
    border-top-color: white;">
  <div class="card-body">

    <form method="get" action="<?=$this->base_url ?>/pdf_rango_tiempo_coordinador" target="_blank">

      <div class="row start-xs">




        <div class="col-xs-12 col-sm-4 col-md-3">
          <label class="field field_v3" id="inputField_fecha">
            <input class="field__input" placeholder="name" id="inputField_fechaInput_inicio" r equired
              name="value_date_inicio">
            <span class="field__label-wrap">
              <span class="field__label">Fecha inicio</span>
            </span>
          </label>
        </div>

        <div class="col-xs-12 col-sm-4 col-md-3">
          <label class="field field_v3" id="inputField_fecha">
            <input class="field__input" placeholder="name" id="inputField_fechaInput_final" required
              name="value_date_final">
            <span class="field__label-wrap">
              <span class="field__label">Fecha final</span>
            </span>
          </label>
        </div>


        <div class="col-xs-12 col-sm-4 col-md-3  ">
          <!--Input css-->
          <label class="field field_v3">
            <input class="field__input" placeholder="name" name="value" required>
            <span class="field__label-wrap">
              <span class="field__label">Buscar</span>
            </span>
          </label>
          <!--Input css-->
        </div>

        <div class="col-xs-12 col-sm-4 col-md-3">

          <button type="submit" id="toolBuscar" class="boton" style="    float: right;
    width: 50px;
    height: 50px;
    /* margin-top: 17px; */
    display: block;
    text-align: center;
    float: right;
    border: none;
    padding: 0px;
    color: white;">

            <i style="font-size: 26px;margin-top: 5px;margin-left: 2px;" class="fas fa-search"></i>
          </button>





        </div>

      </div>

  </div>

  </form>


</div>
</div>
</div>


<div class="linea">

  <h1 class="title">Seccion de Reportes </h1>
</div>
<script>
$(document).ready(function() {
  tippy('#salirBtn', {
    content: 'Salir!',
  });


  $("#inputField_fechaInput_inicio").flatpickr({
    dateFormat: "m-Y",
  });


  $("#inputField_fechaInput_final").flatpickr({
    dateFormat: "m-Y",
  });

});
</script>