<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>

<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/modal.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/HrasExtras.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/tableBoss.css">

<script src='<?=$this->base_url ?>/assets/js/dateTable.js'></script>
<script src='<?=$this->base_url ?>/assets/js/dateTableBoss.js'></script>

<script src='<?=$this->base_url ?>/assets/js/popper_core@2.js'></script>
<script src='<?=$this->base_url ?>/assets/js/tippy@6.js'></script>


<script>
$(document).ready(function() {
  $('#example').DataTable();
});
</script>


<div class="row" style="
    margin-top: -25px;
">
  <div class="col-xs-6">
    <h1 class="h1"> Regirstro de Horas en Revisión </h1>
  </div>

  <div class="col-xs-6" style="
    text-align: end;
    font-size: 30px;
    margin-top: 23px;
">
    <a href="/SysHorasExtras/HrasExtras" id="salirBtn"> <i class="fas fa-sign-out-alt"></i></a>
  </div>
</div>



<div class="card2" style=" background-color: white; margin-top: -2px;
    border-top-color: white;">
  <div class="card-body">


    <table id="example" class="stripe" style="width:100%" style="margin-top: 40px;">
      <thead>
        <tr>
          <th>Departamento</th>
          <th>Fecha</th>
          <th>Total Horas a Pagar Diurnas</th>
          <th>Total Horas a Pagar Nocturnas</th>
          <th>Salary</th>
          <th>Accion</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Tiger Nixon</td>
          <td>System Architect</td>
          <td>Edinburgh</td>
          <td>61</td>
          <td>$320,800</td>
          <td>
            <div style=" margin-top: 25px;"> <a  <i class="fas fa-check-double fa-2x"Style="color: coral;"id="toolAprobar"> </i> </a>
          </td>
        </tr>


        <tr>
          <td>Finn Camacho</td>
          <td>Support Engineer</td>
          <td>San Francisco</td>
          <td>47</td>
          <td>$87,500</td>
          <td>
            <div style=" margin-top: 25px;"> <i class="fas fa-check-double fa-2x" Style="color: coral;" id="toolAprobar"></i></a>
          </td>
        </tr>

      </tbody>

    </table>
  </div>
</div>
<script>
  $(document).ready(function() {
    tippy('#toolAprobar', {
      content: 'Aprobar',
    });
  });
$(document).ready(function() {
  tippy('#salirBtn', {
    content: 'Salir',
  });

});
</script>
