<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/estructuraO.css">


<div class="card">
  <div class="card-body">  

    <h1 class="card-title">Mision</h1>
    <p class="card-text" id="card-text1">Garantizar la seguridad jurídica de las actuaciones de los usuarios
    mediante la publicidad registral y fe pública, en el marco de la legalidad, 
    de procesos expeditos y oportunos; ejerciendo el control de las operaciones 
    a nivel nacional.</p>

    <h1 class="card-title">Vision</h1>
    <p class="card-text" id="card-text2"> Ser un órgano que coadyuve a garantizar la seguridad jurídica de los actos
    protocolizados y autenticados de los usuarios,  mediante un sistema integral 
    de registros y notarías confiable, eficiente, auto-sustentable y transparente.</p>

  </div>

</div>

<?php include (getcwd()."/layout/BottomComponent.phtml")?>