<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/main.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <h1> Mision & Vision </h1>
  </div>
</div>

<h1>Mision</h1>
<p>Garantizar la seguridad jurídica de las actuaciones de los usuarios
   mediante la publicidad registral y fe pública, en el marco de la legalidad, 
   de procesos expeditos y oportunos; ejerciendo el control de las operaciones 
   a nivel nacional.</p>

<h2>Vision</h2>
<p>Ser un órgano que coadyuve a garantizar la seguridad jurídica de los actos
   protocolizados y autenticados de los usuarios,  mediante un sistema integral 
   de registros y notarías confiable, eficiente, auto-sustentable y transparente.</p>




  <?php include (getcwd()."/layout/BottomComponent.phtml")?>