<?php include (getcwd()."/layout/TopComponent.phtml")?>
<?php include (getcwd()."/layout/HeaderComponent.phtml")?>
<?php include (getcwd()."/layout/MenuComponent.phtml")?>
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/modal.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/css/HrasExtras.css">
<link rel="stylesheet" type="text/css" href="<?=$this->base_url ?>/assets/fontawesome/css/all.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/flexboxgrid.min.css">
<link rel="stylesheet" type="text/css" href="<?= $this->base_url ?>/assets/css/main.css">
<body style ="background-image:none;">
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4">
    <h1> Organigrama </h1>
  </div>
</div>

<div class="container" id="container">
    

<div style="    text-align: center;">
          <img src="<?=$this->base_url?>/assets/img/organigramasaren.jpg" style="width: 100%" />
        </div>



  </div>
</body>




  <?php include (getcwd()."/layout/BottomComponent.phtml")?>